server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.129.65.158:8090 # 配置Nginx地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
