server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848 # 配置Nacos地址
        server-addr: 8.129.65.158:8090 # 配置Nginx地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
