server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/progzc/springcloud-config.git # 存放配置文件的github路径
          search-paths:
            - springcloud-config
      label: main

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
