server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/progzc/springcloud-config.git # 存放配置文件的github路径
          search-paths:
            - springcloud-config
      label: main
  rabbitmq:
    host: 8.129.65.158 # 不要配置成http://8.129.65.158
    port: 5672 # 15672是web管理界面的端口，5672是MQ访问的端口
    username: admin
    password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
